#include <Arduino.h>

String testJSON = R"rawliteral(
{
 "lines":[
  {
   "logic":{
     "type":"OP",
     "op":"OR",
     "nodes":[
       {
         "type":"OP",
         "op":"OR",
         "nodes":[
           {"type":"CONTACT","pin":"I0","mode":"NO"},
           {"type":"CONTACT","pin":"I1","mode":"NO"}
         ]
       },
       {"type":"CONTACT","pin":"I2","mode":"NO"}
     ]
   },
   "outputs":[
     {"pin":"Q0","type":"COIL"},
     {"pin":"Q1","type":"COIL"}
   ]
  }
 ]
}
)rawliteral";

String testJSON2 = R"rawliteral(
{
 "lines":[
  {
    "logic":{
      "type":"OP",
      "op":"AND",
      "nodes":[
        {
          "type":"OP",
          "op":"OR",
          "nodes":[
            {
              "type":"OP",
              "op":"AND",
              "nodes":[
                {"type":"CONTACT","pin":"I0","mode":"NC"},
                {"type":"CONTACT","pin":"I1","mode":"NC"}
              ]
            },
            {"type":"CONTACT","pin":"Q0","mode":"NO"}
          ]
        },
        {"type":"CONTACT","pin":"I2","mode":"NO"}
      ]
    },
    "outputs":[
      {"pin":"Q0","type":"COIL"},
      {"pin":"Q1","type":"COIL"}
    ]
  }
 ]
}
)rawliteral";

String testJSON3 = R"rawliteral(
{
 "lines":[
  {
    "logic":{
      "type":"OP",
      "op":"AND",
      "nodes":[
        {
          "type":"OP",
          "op":"OR",
          "nodes":[
            {
              "type":"OP",
              "op":"AND",
              "nodes":[
                {"type":"CONTACT","pin":"I0","mode":"NC"},
                {"type":"CONTACT","pin":"I1","mode":"NC"}
              ]
            },
            {"type":"CONTACT","pin":"Q0","mode":"NO"}
          ]
        },
        {"type":"CONTACT","pin":"I2","mode":"NO"}
      ]
    },
    "outputs":[
      {"pin":"Q0","type":"COIL"},
      {"pin":"M0","type":"COIL"}
    ]
  },
  {
    "logic":{
              "type":"OP",
              "op":"AND",
              "nodes":[
                {"type":"CONTACT","pin":"M0","mode":"NO"},
                {"type":"CONTACT","pin":"I3","mode":"NC"}
              ]
    },
    "outputs":[
      {"pin":"Q1","type":"COIL"}
    ]
  }
 ]
}
)rawliteral";

String testJSON4 = R"rawliteral(
{
 "lines":[
  {
   "logic":{
     "type":"CONTACT",
     "pin":"I0",
     "mode":"NC"
   },
   "outputs":[
     {"pin":"M0","type":"SET"}
   ]
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"I1",
     "mode":"NC"
   },
   "outputs":[
     {"pin":"M0","type":"RESET"}
   ]
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"M0",
     "mode":"NO"
   },
   "outputs":[
     {"pin":"Q0","type":"COIL"}
   ]
  }
 ]
}
)rawliteral";

String testJSON5 = R"rawliteral(
{
 "lines":[
  {
   "logic":{
     "type":"OP",
     "op":"AND",
     "nodes":[
       {
         "type":"OP",
         "op":"OR",
         "nodes":[
           {"type":"CONTACT","pin":"I0","mode":"NC"},
           {"type":"CONTACT","pin":"M0","mode":"NO"}
         ]
       },
       {"type":"CONTACT","pin":"I1","mode":"NO"}
     ]
   },
   "outputs":[
     {"pin":"M0","type":"COIL"}
   ]
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"M0",
     "mode":"NO"
   },
   "timer":{
     "type":"TON",
     "name":"T0",
     "preset":3000
   }
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"T0.DN",
     "mode":"NO"
   },
   "outputs":[
     {"pin":"Q0","type":"COIL"}
   ]
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"T0.TT",
     "mode":"NO"
   },
   "outputs":[
     {"pin":"Q1","type":"COIL"}
   ]
  },
  {
  "logic":{
    "type":"CONTACT",
    "pin":"I2",
    "mode":"NC"
  },
  "outputs":[
    {"pin":"T0","type":"RESET"}
  ]
  }
 ]
}
)rawliteral";

String testJSON6 = R"rawliteral(
{
 "lines":[
  {
   "logic":{
     "type":"CONTACT",
     "pin":"I0",
     "mode":"NC"
   },
   "timer":{
     "type":"TOF",
     "name":"T0",
     "preset":3000
   }
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"T0.DN",
     "mode":"NO"
   },
   "outputs":[
     {"pin":"Q0","type":"COIL"}
   ]
  }
 ]
}
)rawliteral";

String testJSON7 = R"rawliteral(
{
 "lines":[
  {
   "logic":{
     "type":"F_TRIG",
     "pin":"I0"
   },
   "outputs":[
     {"pin":"M0","type":"SET"}
   ]
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"M0",
     "mode":"NO"
   },
   "outputs":[
     {"pin":"Q0","type":"COIL"}
   ]
  }
 ]
}
)rawliteral";

String testJSON8 = R"rawliteral(
{
 "lines":[
  {
   "logic":{
     "type":"R_TRIG",
     "pin":"I0"
   },
   "counter":{
     "type":"CTU",
     "name":"C0",
     "preset":3
   }
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"C0.DN",
     "mode":"NO"
   },
   "outputs":[
     {"pin":"Q0","type":"COIL"}
   ]
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"I1",
     "mode":"NC"
   },
   "outputs":[
     {"pin":"C0","type":"RESET"}
   ]
  }
 ]
}
)rawliteral";

String testJSON9 = R"rawliteral(
{
 "lines":[
  {
   "logic":{
     "type":"OP",
     "op":"AND",
     "nodes":[
       {
         "type":"OP",
         "op":"OR",
         "nodes":[
           {"type":"CONTACT","pin":"I0","mode":"NC"},
           {"type":"CONTACT","pin":"M0","mode":"NO"}
         ]
       },
       {"type":"CONTACT","pin":"I1","mode":"NO"}
     ]
   },
   "outputs":[
     {"pin":"M0","type":"COIL"}
   ]
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"M0",
     "mode":"NO"
   },
   "timer":{
     "type":"TON",
     "name":"T0",
     "preset":3000
   }
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"T0.DN",
     "mode":"NO"
   },
   "outputs":[
     {"pin":"Q0","type":"COIL"}
   ]
  },
  {
   "logic":{
     "type":"CONTACT",
     "pin":"T0.TT",
     "mode":"NO"
   },
   "outputs":[
     {"pin":"Q1","type":"COIL"}
   ]
  },
  {
  "logic":{
    "type":"F_TRIG",
    "pin":"I2"
  },
  "counter":{
     "type":"CTU",
     "name":"C0",
     "preset":3
   }
  },
  {
  "logic":{
    "type":"CONTACT",
    "pin":"C0.DN",
    "mode":"NO"
  },
  "outputs":[
    {"pin":"T0","type":"RESET"},
    {"pin":"C0","type":"RESET"}
  ]
  }
 ]
}
)rawliteral";